include:
  - board: seeeduino_xiao_ble
    shield: zenith_left

  - board: seeeduino_xiao_ble
    shield: zenith_right    

  - board: seeeduino_xiao_ble
    shield: settings_reset

  - board: nice_nano_v2
    shield: settings_reset
    
  - board: nice_nano_v2
    shield: zenith_dongle dongle_display


