CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
# dongle mode
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

# Enable the dongle display features
CONFIG_ZMK_DISPLAY=y

# Show the battery level of the peripherals
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60

# Enable MacOS modifier symbols instead of Windows (Optional)
CONFIG_ZMK_DONGLE_DISPLAY_MAC_MODIFIERS=y

# Enable WPM Widget
CONFIG_ZMK_DONGLE_DISPLAY_WPM=y

# Customize Layer Name Text Alignment (left, center, or right)
CONFIG_ZMK_DONGLE_DISPLAY_LAYER_TEXT_ALIGN="center"
